# Generated by Django 4.2.2 on 2023-06-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminTG', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='number',
            field=models.TextField(default='Введите номер', max_length=25),
        ),
    ]
