# Generated by Django 4.2.2 on 2023-06-21 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminTG', '0004_alter_text_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='number',
        ),
    ]
