# Generated by Django 4.2.2 on 2023-06-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminTG', '0005_remove_text_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='title',
            field=models.CharField(default='Название', max_length=30),
        ),
    ]
